export const profileFieldLabels: Record<string, string> = {
  name: 'Nome completo',
  cpf: 'CPF',
  birthDate: 'Data de nascimento',
  email: 'E-mail',
  phone: 'Telefone/celular',
  zipCode: 'CEP',
  address: 'Endereço',
  housing: 'Tipo de moradia',
  hasOutdoorArea: 'Área externa segura',
  dailyTime: 'Tempo disponível por dia',
  activityLevel: 'Nível de atividade',
  hasChildren: 'Crianças na residência',
  hasOtherPets: 'Outros pets na residência',
  experience: 'Experiência com animais',
  acceptsSpecialCare: 'Disponibilidade para cuidados especiais',
  preferredSpecies: 'Espécie desejada',
  preferredSize: 'Porte desejado',
}
